Update prova.yml

diff --git a/.github/workflows/prova.yml b/.github/workflows/prova.yml
--- a/.github/workflows/prova.yml
+++ b/.github/workflows/prova.yml
@@ -14,142 +14,31 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v1
-    # Standard drop-in approach that should work for most people.
-    - uses: ammaraskar/sphinx-action@master
-      with:
-        docs-folder: "docs/"
-        build-command: "sphinx-build -b html . _build"
-
-    - uses: actions/upload-artifact@v1
-      with:
-        name: DocumentationHTML
-        path: docs/_build/
-
-    - name: Commit documentation changes
-      run: |
-        pwd
-        git clone https://github.com/mattia-donato/mattia-donato.github.io.git
-        ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'        
-        cp -rv docs/_build/* mattia-donato.github.io/prova/
-        cd mattia-donato.github.io
-        touch .nojekyll
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add . -v
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-        ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
-        
-        git clone "https://github.com/VicidominiLab/BrightEyes-TTM.git" BrightEyes-TTM
-        
-        ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
-        
-#     - uses: actions/checkout@v1
-    # Standard drop-in approach that should work for most people.
-    - uses: ammaraskar/sphinx-action@master
-      with:
-        pre-build-command: |
-                           ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
-                           pip install myst-parser[linkify] sphinx-rtd-theme
-
-        docs-folder: "mattia-donato.github.io/BrightEyes-TTM/docs/source"          
-        build-command: "sphinx-build -b html . _build"
-
-    - name: Check situation
-      run: |
-           cp -rv mattia-donato.github.io/BrightEyes-TTM/docs/source/_build/* mattia-donato.github.io/prova/
+    - name: Initial Situation
+    -  run: |
            find . -type d
-           echo -
-           echo $HOME
-           
-    - uses: actions/upload-artifact@v1
-      with:
-        name: DocumentationHTML bis
-        path: mattia-donato.github.io/BrightEyes-TTM/docs/source/_build/
+    - name: Initial Situation           
+    - uses: actions/checkout@v3
+    -  run: |
+           find . -type d
     
-    - name: Commit documentation changes
-      run: |
-           pwd
-           find . -type d      
-           cd mattia-donato.github.io/BrightEyes-TTM/docs/source
-           git config --local user.email "action@github.com"
-           git config --local user.name "GitHub Action"           
-           cp -R _build ./docs/
-           cd ./docs/
-           git add . -v
-           git commit -m "Update documentation" -a || true
-           find  -type d
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-              github_token: ${{ secrets.GITHUB_TOKEN }}
-              branch: ${{ github.ref }}
-
-
-# name: Prova
-
-# on:
-#   # Triggers the workflow on push or pull request events but only for the "main" branch
-#   push:
-#     branches: [ "main" ]
-    
-#   pull_request:
-#     branches: [ "main" ]
-    
-# # permissions:
-# #   contents: read
-# #   pages: write
-# #   id-token: write
-
-# # concurrency:
-# #   group: "pages"
-# #   cancel-in-progress: true
-
-# jobs:
-#   build:
-
-#     runs-on: ubuntu-latest
-
-#     steps:
-#     - uses: actions/checkout@v1
 #     # Standard drop-in approach that should work for most people.
-#     - uses: ammaraskar/sphinx-action@master
-#       with:
-#         docs-folder: "docs/"
-#         build-command: "sphinx-build -b html . _build"
-# #     # Example of using a custom build-command.
 # #     - uses: ammaraskar/sphinx-action@master
 # #       with:
-# #         build-command: "sphinx-build -b html . _build"
-# #         docs-folder: "docs2/"
-#     # Grabbing custom dependencies and building as a pdf.
-# #     - uses: ammaraskar/sphinx-action@master
-# #       with:
-# #         pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
-# #         build-command: "make latexpdf"
 # #         docs-folder: "docs/"
-#     # Great extra actions to compose with:
-#     # Create an artifact of the html output.
-#     - uses: actions/upload-artifact@v1
-#       with:
-#         name: DocumentationHTML
-#         path: docs/_build/
-# #     # Create an artifact out of the previously built pdf.
+# #         build-command: "sphinx-build -b html . _build"
+
 # #     - uses: actions/upload-artifact@v1
 # #       with:
-# #         name: Documentation
-# #         path: docs2/_build/latex/pdfexample.pdf
-#     # Publish built docs to gh-pages branch.
-#     # ===============================
-        
+# #         name: DocumentationHTML
+# #         path: docs/_build/
+
 #     - name: Commit documentation changes
 #       run: |
-#         git clone https://github.com/mattia-donato/mattia-donato.github.io.git
-#         ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'        
-#         cp -r docs/_build/* mattia-donato.github.io/prova/
-#         cd mattia-donato.github.io
+#         pwd
+#         git clone "https://github.com/VicidominiLab/BrightEyes-TTM.git" BrightEyes-TTM
+#         cp -rv mattia-donato.github.io/BrightEyes-TTM/docs/source/* prova/        
+#         ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'                
 #         touch .nojekyll
 #         git config --local user.email "action@github.com"
 #         git config --local user.name "GitHub Action"
@@ -158,86 +47,157 @@ jobs:
 #         # The above command will fail if no changes were present, so we ignore
 #         # that.
 #         ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
-        
-#         git clone "https://github.com/VicidominiLab/BrightEyes-TTM.git" BrightEyes-TTM
+    
         
 #         ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
         
-#     - uses: actions/checkout@v1
+# #     - uses: actions/checkout@v1
 #     # Standard drop-in approach that should work for most people.
 #     - uses: ammaraskar/sphinx-action@master
 #       with:
-#         docs-folder: "BrightEyes-TTM/docs/"
+#         pre-build-command: |
+#                            ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
+#                            pip install myst-parser[linkify] sphinx-rtd-theme
+
+#         docs-folder: "mattia-donato.github.io/BrightEyes-TTM/docs/source"          
 #         build-command: "sphinx-build -b html . _build"
-# #     # Example of using a custom build-command.
-# #     - uses: ammaraskar/sphinx-action@master
-# #       with:
-# #         build-command: "sphinx-build -b html . _build"
-# #         docs-folder: "docs2/"
-#     # Grabbing custom dependencies and building as a pdf.
-# #     - uses: ammaraskar/sphinx-action@master
-# #       with:
-# #         pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
-# #         build-command: "make latexpdf"
-# #         docs-folder: "docs/"
-#     # Great extra actions to compose with:
-#     # Create an artifact of the html output.
+
+#     - name: Check situation
+#       run: |
+#            find . -type d
+#            echo -
+#            echo $HOME
+           
 #     - uses: actions/upload-artifact@v1
 #       with:
-#         name: DocumentationHTML
-#         path: BrightEyes-TTM/docs/_build/
-        
-#     # ===============================
+#         name: DocumentationHTML bis
+#         path: mattia-donato.github.io/BrightEyes-TTM/docs/source/_build/
     
+#     - name: Commit documentation changes
+#       run: |
+#            pwd
+#            find . -type d      
+#            cd mattia-donato.github.io/BrightEyes-TTM/docs/source
+#            git config --local user.email "action@github.com"
+#            git config --local user.name "GitHub Action"           
+#            cp -R _build ./docs/
+#            cd ./docs/
+#            git add . -v
+#            git commit -m "Update documentation" -a || true
+#            find  -type d
 #     - name: Push changes
 #       uses: ad-m/github-push-action@master
 #       with:
 #               github_token: ${{ secrets.GITHUB_TOKEN }}
 #               branch: ${{ github.ref }}
-# #   deploy:
-# #     environment:
-# #       name: github-pages
-# #       url: ${{ steps.deployment.outputs.page_url }}
-# #     runs-on: ubuntu-latest
-# #     steps:
-# #       - name: Checkout
-# #         uses: actions/checkout@v3
-# #       - name: Setup Pages
-# #         uses: actions/configure-pages@v2
-# #       - name: Upload artifact
-# #         uses: actions/upload-pages-artifact@v1
-# #         with:
-# #           # Upload entire repository
-# #           path: '.'
-# #       - name: Deploy to GitHub Pages
-# #         id: deployment
-# #         uses: actions/deploy-pages@v1
 
 
-# # # # # Simple workflow for deploying static content to GitHub Pages
-# # # # name: Deploy static content to Pages
+# # name: Prova
 
-# # # # on:
-# # # #   # Runs on pushes targeting the default branch
-# # # #   push:
-# # # #     branches: ["main"]
+# # on:
+# #   # Triggers the workflow on push or pull request events but only for the "main" branch
+# #   push:
+# #     branches: [ "main" ]
+    
+# #   pull_request:
+# #     branches: [ "main" ]
+    
+# # # permissions:
+# # #   contents: read
+# # #   pages: write
+# # #   id-token: write
 
-# # # #   # Allows you to run this workflow manually from the Actions tab
-# # # #   workflow_dispatch:
-
-# # # # # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
-# # # # permissions:
-# # # #   contents: read
-# # # #   pages: write
-# # # #   id-token: write
-
-# # # # Allow one concurrent deployment
 # # # concurrency:
 # # #   group: "pages"
 # # #   cancel-in-progress: true
 
-# # # jobs:
-# # #   # Single deploy job since we're just deploying
+# # jobs:
+# #   build:
+
+# #     runs-on: ubuntu-latest
+
+# #     steps:
+# #     - uses: actions/checkout@v1
+# #     # Standard drop-in approach that should work for most people.
+# #     - uses: ammaraskar/sphinx-action@master
+# #       with:
+# #         docs-folder: "docs/"
+# #         build-command: "sphinx-build -b html . _build"
+# # #     # Example of using a custom build-command.
+# # #     - uses: ammaraskar/sphinx-action@master
+# # #       with:
+# # #         build-command: "sphinx-build -b html . _build"
+# # #         docs-folder: "docs2/"
+# #     # Grabbing custom dependencies and building as a pdf.
+# # #     - uses: ammaraskar/sphinx-action@master
+# # #       with:
+# # #         pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
+# # #         build-command: "make latexpdf"
+# # #         docs-folder: "docs/"
+# #     # Great extra actions to compose with:
+# #     # Create an artifact of the html output.
+# #     - uses: actions/upload-artifact@v1
+# #       with:
+# #         name: DocumentationHTML
+# #         path: docs/_build/
+# # #     # Create an artifact out of the previously built pdf.
+# # #     - uses: actions/upload-artifact@v1
+# # #       with:
+# # #         name: Documentation
+# # #         path: docs2/_build/latex/pdfexample.pdf
+# #     # Publish built docs to gh-pages branch.
+# #     # ===============================
+        
+# #     - name: Commit documentation changes
+# #       run: |
+# #         git clone https://github.com/mattia-donato/mattia-donato.github.io.git
+# #         ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'        
+# #         cp -r docs/_build/* mattia-donato.github.io/prova/
+# #         cd mattia-donato.github.io
+# #         touch .nojekyll
+# #         git config --local user.email "action@github.com"
+# #         git config --local user.name "GitHub Action"
+# #         git add . -v
+# #         git commit -m "Update documentation" -a || true
+# #         # The above command will fail if no changes were present, so we ignore
+# #         # that.
+# #         ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
+        
+# #         git clone "https://github.com/VicidominiLab/BrightEyes-TTM.git" BrightEyes-TTM
+        
+# #         ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
+        
+# #     - uses: actions/checkout@v1
+# #     # Standard drop-in approach that should work for most people.
+# #     - uses: ammaraskar/sphinx-action@master
+# #       with:
+# #         docs-folder: "BrightEyes-TTM/docs/"
+# #         build-command: "sphinx-build -b html . _build"
+# # #     # Example of using a custom build-command.
+# # #     - uses: ammaraskar/sphinx-action@master
+# # #       with:
+# # #         build-command: "sphinx-build -b html . _build"
+# # #         docs-folder: "docs2/"
+# #     # Grabbing custom dependencies and building as a pdf.
+# # #     - uses: ammaraskar/sphinx-action@master
+# # #       with:
+# # #         pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
+# # #         build-command: "make latexpdf"
+# # #         docs-folder: "docs/"
+# #     # Great extra actions to compose with:
+# #     # Create an artifact of the html output.
+# #     - uses: actions/upload-artifact@v1
+# #       with:
+# #         name: DocumentationHTML
+# #         path: BrightEyes-TTM/docs/_build/
+        
+# #     # ===============================
+    
+# #     - name: Push changes
+# #       uses: ad-m/github-push-action@master
+# #       with:
+# #               github_token: ${{ secrets.GITHUB_TOKEN }}
+# #               branch: ${{ github.ref }}
 # # #   deploy:
 # # #     environment:
 # # #       name: github-pages
@@ -256,3 +216,47 @@ jobs:
 # # #       - name: Deploy to GitHub Pages
 # # #         id: deployment
 # # #         uses: actions/deploy-pages@v1
+
+
+# # # # # # Simple workflow for deploying static content to GitHub Pages
+# # # # # name: Deploy static content to Pages
+
+# # # # # on:
+# # # # #   # Runs on pushes targeting the default branch
+# # # # #   push:
+# # # # #     branches: ["main"]
+
+# # # # #   # Allows you to run this workflow manually from the Actions tab
+# # # # #   workflow_dispatch:
+
+# # # # # # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+# # # # # permissions:
+# # # # #   contents: read
+# # # # #   pages: write
+# # # # #   id-token: write
+
+# # # # # Allow one concurrent deployment
+# # # # concurrency:
+# # # #   group: "pages"
+# # # #   cancel-in-progress: true
+
+# # # # jobs:
+# # # #   # Single deploy job since we're just deploying
+# # # #   deploy:
+# # # #     environment:
+# # # #       name: github-pages
+# # # #       url: ${{ steps.deployment.outputs.page_url }}
+# # # #     runs-on: ubuntu-latest
+# # # #     steps:
+# # # #       - name: Checkout
+# # # #         uses: actions/checkout@v3
+# # # #       - name: Setup Pages
+# # # #         uses: actions/configure-pages@v2
+# # # #       - name: Upload artifact
+# # # #         uses: actions/upload-pages-artifact@v1
+# # # #         with:
+# # # #           # Upload entire repository
+# # # #           path: '.'
+# # # #       - name: Deploy to GitHub Pages
+# # # #         id: deployment
+# # # #         uses: actions/deploy-pages@v1
